name: CxONE-scan-on-pull-request-Gh-Action
on:
  pull_request:
    types: [opened, reopened, synchronize] #Types specify which pull request events will trigger the workflow. For more events refer Github Actions documentation.
    branches:
      - main
      
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST Github Action
        # You may pin to the exact commit or the version.
        # uses: Checkmarx/ast-github-action@0fcee7e03446692b38464ac6ec3a47bf1deb1c27
        uses: Checkmarx/ast-github-action@2.0.9
        with:
          base_uri: https://ast.checkmarx.net/
          cx_tenant: kelsey-na
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.CLIENT_SECRET }}
          #project_name:
          # optional, default is ${{ github.repository }}
          #branch:
          # optional, default is ${{ github.head_ref || github.ref }}
          # GitHub API Token
          #github_token:
          # optional, default is ${{ github.token }}
          # Additional parameters for AST scan
          additional_params:  --scan-types sast, sca, kics --file-filter !readme --report-format sarif --output-name results 
          #--sast-filter !src/main/webapp
          #repo_name:
          # optional, default is ${{ github.event.repository.name }}
          # Organization name to create the Pr comment
          #namespace:
          # optional, default is ${{ github.repository_owner }}
          # Pr Number of the pull request that needs the decoration
          #pr_number:
          # optional, default is ${{ github.event.number }}
      
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
